./1_update_system.sh
./2_install_python.sh
./3_install_postgres.sh
./4_clone_project.sh
./5_run_project.sh
./6_install_gateway.sh
./7_install_webserver.sh
./8_add_webite.sh
./9_install_supervisor.sh          