#!/bin/bash
set -e
exec > >(sudo tee /var/log/transfer_installer.log | logger -t transfer_installer -s) 2>&1
whoami
sudo yum -y install wget unzip
whoami
TARGET_DIRECTORY="/usr/src/"
sudo mkdir -p "$TARGET_DIRECTORY"
cd $TARGET_DIRECTORY
whoami
sudo wget https://github.com/oreaba/install_transfer_backend/archive/main.zip 
sudo unzip main.zip
sudo mv main.zip transfer_installer.zip
sudo mv install_transfer_backend-main transfer_installer
cd transfer_installer
sudo chmod +x *.*
whoami
./1_update_system.sh
./2_install_python.sh
./3_install_postgres.sh
./4_setup_ssh.sh
./5_clone_project.sh
./6_run_project.sh
./7_install_gateway.sh
./8_install_webserver.sh
./9_add_webite.sh
./10_install_supervisor.sh