#!/bin/bash
hostnamectl
echo "Logged user:"
whoami
set -e
exec > >(sudo tee /var/log/transfer_installer.log | logger -t transfer_installer -s) 2>&1
yum -y install wget unzip
TARGET_DIRECTORY="/usr/src/"
sudo mkdir -p "$TARGET_DIRECTORY"
cd $TARGET_DIRECTORY
wget https://github.com/oreaba/install_transfer_backend/archive/main.zip 
unzip main.zip
mv main.zip transfer_installer.zip
mv install_transfer_backend-main transfer_installer
cd transfer_installer
sudo chmod +x *.*
# ./1_update_system.sh
# ./2_install_python.sh
./3_install_postgres.sh
./4_setup_ssh.sh #> /var/log/4_clone_project.log 2>&1
./5_clone_project.sh #> /var/log/5_clone_project.log 2>&1
# ./6_run_project.sh #>/var/log/6_run_project.log 2>&1
# ./7_install_gateway.sh
./8_install_webserver.sh
./9_add_website.sh
./10_install_supervisor.sh