#!/bin/bash
hostnamectl
echo "Logged user:"
whoami
# set -e
exec > >(sudo tee /var/log/transfer_installer.log | logger -t transfer_installer -s) 2>&1
yum -y install wget unzip
TARGET_DIRECTORY="/usr/src/"
PROJECT_DIRECTORY="transfer_installer/"
sudo mkdir -p "$TARGET_DIRECTORY"
cd $TARGET_DIRECTORY
wget https://github.com/oreaba/install_transfer_backend/archive/main.zip 
unzip -o main.zip
mv main.zip transfer_installer.zip
# mv install_transfer_backend-main transfer_installer
rsync -a install_transfer_backend-main/ transfer_installer/
cd $TARGET_DIRECTORY$PROJECT_DIRECTORY
sudo chmod +x *.*
source /usr/src/transfer_installer/1_update_system.sh
source /usr/src/transfer_installer/2_install_python.sh
source /usr/src/transfer_installer/3_install_postgres.sh
source /usr/src/transfer_installer/4_setup_ssh.sh #> /var/log/4_clone_project.log 2>&1
source /usr/src/transfer_installer/5_clone_project.sh #> /var/log/5_clone_project.log 2>&1
source /usr/src/transfer_installer/6_run_project.sh #>/var/log/6_run_project.log 2>&1
source /usr/src/transfer_installer/7_install_gateway.sh
source /usr/src/transfer_installer/8_install_webserver.sh
source /usr/src/transfer_installer/9_add_website.sh
source /usr/src/transfer_installer/10_install_supervisor.sh